spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: "static/**, public/**"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/sandbox
    username: h2
    password: P@s5w0rd
    initialization-mode: embedded
