name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ui/
    - run: npm install
    - run: npx jest --coverage 
    - run: |
      mkdir ../coverage/
      cp -r ./coverage/ ../coverage/
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage/

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ui/
    - run: npm install
    - run: npm run build
    - run: |
      mkdir ../artifacts/
      cp -r ./dist/ ../artifacts/
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ui
        path: artifacts/