# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        cd api/
        chmod +x ./gradlew
         ./gradlew build
    - run: |
        mkdir artifacts/
        cp api/build/libs/*.jar artifacts/
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: api
        path: artifacts/